name: Deploy Helm Chart on WSL Minikube

on:
  push:
    branches:
      - main
  
  workflow_dispatch:


jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Install Helm
    #   run: |
    #     curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy Helm Charts
      run: |
        for chart in ./helm/*; do
          if [ -d "$chart" ]; then
            chart_name=$(basename "$chart")
            helm upgrade --install "$chart_name" "$chart" --namespace "$chart_name" --create-namespace
          fi
        done
